"""
Executive Summary report generator.

Renders HTML report with Jinja2 into artifacts/experiments/<experiment_id>/exec_summary.html.
Includes: objective, hypothesis, population, metrics, sample size, SRM,
main result (lift + CI), segment highlights, decision recommendation, risks/assumptions.
"""

import json
import logging
from pathlib import Path
from typing import Any, Dict, Optional

logger = logging.getLogger(__name__)

REPORT_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Executive Summary - {{ experiment_id }}</title>
    <style>
        body { font-family: 'Segoe UI', Tahoma, sans-serif; max-width: 900px; margin: 40px auto; padding: 20px; color: #333; }
        h1 { color: #1a5276; border-bottom: 2px solid #1a5276; padding-bottom: 8px; }
        h2 { color: #2874a6; margin-top: 28px; }
        .card { background: #f8f9fa; border-radius: 8px; padding: 16px; margin: 16px 0; border-left: 4px solid #1a5276; }
        .metric { display: inline-block; margin: 8px 16px 8px 0; }
        .metric-value { font-size: 1.4em; font-weight: bold; color: #1a5276; }
        .recommendation { font-size: 1.2em; padding: 16px; border-radius: 8px; margin: 20px 0; font-weight: 600; }
        .recommendation.ship { background: #d5f5e3; border: 1px solid #27ae60; color: #196f3d; }
        .recommendation.hold { background: #fdebd0; border: 1px solid #f39c12; color: #b7950b; }
        .recommendation.iterate { background: #ebf5fb; border: 1px solid #3498db; color: #1a5276; }
        table { border-collapse: collapse; width: 100%; margin: 16px 0; }
        th, td { border: 1px solid #bdc3c7; padding: 10px; text-align: left; }
        th { background: #ecf0f1; font-weight: 600; }
        .srm-pass { color: #27ae60; }
        .srm-fail { color: #e74c3c; }
        .footer { margin-top: 40px; font-size: 0.9em; color: #7f8c8d; }
    </style>
</head>
<body>
    <h1>Executive Summary: {{ experiment_id }}</h1>
    <p><strong>Analysis Date:</strong> {{ analysis_timestamp }}</p>
    <p>{{ objective }}</p>

    <h2>Experiment Design</h2>
    <div class="card">
        <p><strong>Hypothesis:</strong> {{ hypothesis }}</p>
        <p><strong>Population:</strong> {{ population }}</p>
        <p><strong>Primary Metric:</strong> {{ primary_metric }}</p>
        <p><strong>Allocation:</strong> {{ allocation_pct }}% treatment / {{ 100 - allocation_pct }}% control</p>
        <p><strong>Sample Size:</strong> Control N={{ control_n }}, Treatment N={{ treatment_n }}</p>
    </div>

    <h2>Sample Ratio Mismatch (SRM)</h2>
    <p class="{{ 'srm-pass' if srm_passed else 'srm-fail' }}">
        {% if srm_passed %}✓ SRM check passed (p={{ srm_p_str }}){% else %}
        ✗ SRM detected (p={{ srm_p_str }}) - allocation deviates from expected{% endif %}
    </p>

    <h2>Key Results</h2>
    <div class="metric">Control Mean: <span class="metric-value">{{ control_mean_str }}</span></div>
    <div class="metric">Treatment Mean: <span class="metric-value">{{ treatment_mean_str }}</span></div>
    <div class="metric">Lift: <span class="metric-value">{{ lift_str }}</span> ({{ lift_pct_str }}%)</div>
    <div class="metric">95% CI: [{{ ci_low_str }}, {{ ci_high_str }}]</div>
    <div class="metric">p-value: <span class="metric-value">{{ p_value_str }}</span></div>
    {% if cuped_applied %}
    <p><em>CUPED applied. Variance reduction: {{ var_red_str }}%</em></p>
    {% endif %}

    {% if segments %}
    <h2>Segment Highlights</h2>
    <table>
        <tr><th>Segment</th><th>Value</th><th>Control N</th><th>Treatment N</th><th>Lift</th><th>p-value</th><th>Significant</th></tr>
        {% for s in segments[:10] %}
        <tr>
            <td>{{ s.segment_name }}</td><td>{{ s.segment_value }}</td>
            <td>{{ s.control_n }}</td><td>{{ s.treatment_n }}</td>
            <td>{{ s.lift_str }}</td><td>{{ s.p_value_str }}</td>
            <td>{{ "Yes" if s.significant else "No" }}</td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}

    <h2>Decision Recommendation</h2>
    <div class="recommendation {{ recommendation }}">
        {{ recommendation|upper }}: {{ recommendation_reason }}
    </div>

    <h2>Risks & Assumptions</h2>
    <ul>
        <li>Results assume no external confounding during experiment period.</li>
        <li>Sample size may limit detection of small effects.</li>
        {% if not srm_passed %}
        <li><strong>SRM detected:</strong> Randomization may have been compromised.</li>
        {% endif %}
    </ul>

    <div class="footer">
        Generated by Telco Retention Decision Studio. For internal use only.
    </div>
</body>
</html>
"""


def render_exec_summary(
    analysis_result: Dict[str, Any],
    experiment_id: str,
    output_path: Optional[Path] = None,
    artifacts_dir: str = "artifacts/experiments",
) -> Path:
    """
    Render executive summary HTML report.
    
    Args:
        analysis_result: AnalysisResult.to_dict() or equivalent
        experiment_id: Experiment ID
        output_path: Override output path
        artifacts_dir: Base artifacts directory
        
    Returns:
        Path to generated HTML file
    """
    try:
        from jinja2 import Template
    except ImportError:
        Template = None
    
    out_path = output_path or Path(artifacts_dir) / experiment_id / "exec_summary.html"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    
    control = analysis_result.get("control_stats", {})
    treatment = analysis_result.get("treatment_stats", {})
    
    def _fmt(v, prec=4):
        if v is None: return "—"
        return f"{v:.{prec}f}"
    
    segs = analysis_result.get("segments", [])
    for s in segs:
        s["lift_str"] = _fmt(s.get("lift"))
        s["p_value_str"] = _fmt(s.get("p_value"))
    
    context = {
        "experiment_id": experiment_id,
        "analysis_timestamp": analysis_result.get("analysis_timestamp", ""),
        "objective": "Evaluate retention campaign impact on customer churn.",
        "hypothesis": "Treatment reduces churn rate compared to control.",
        "population": "High-risk customers identified by churn model.",
        "primary_metric": analysis_result.get("primary_metric", "churn_rate"),
        "allocation_pct": int(100 * analysis_result.get("expected_allocation", 0.5)),
        "control_n": control.get("n", 0),
        "treatment_n": treatment.get("n", 0),
        "srm_passed": analysis_result.get("srm_passed", True),
        "srm_p_value": analysis_result.get("srm_p_value"),
        "srm_p_str": _fmt(analysis_result.get("srm_p_value") or 1),
        "control_mean": control.get("mean", 0),
        "treatment_mean": treatment.get("mean", 0),
        "control_mean_str": _fmt(control.get("mean", 0)),
        "treatment_mean_str": _fmt(treatment.get("mean", 0)),
        "lift": analysis_result.get("lift", 0),
        "lift_str": _fmt(analysis_result.get("lift", 0)),
        "lift_pct": analysis_result.get("lift_pct"),
        "lift_pct_str": _fmt(analysis_result.get("lift_pct") or 0, 2),
        "ci_low": analysis_result.get("ci_low", 0),
        "ci_high": analysis_result.get("ci_high", 0),
        "ci_low_str": _fmt(analysis_result.get("ci_low", 0)),
        "ci_high_str": _fmt(analysis_result.get("ci_high", 0)),
        "p_value": analysis_result.get("p_value", 1),
        "p_value_str": _fmt(analysis_result.get("p_value", 1)),
        "cuped_applied": analysis_result.get("cuped_applied", False),
        "variance_reduction_pct": analysis_result.get("variance_reduction_pct"),
        "var_red_str": _fmt(analysis_result.get("variance_reduction_pct") or 0, 1),
        "segments": segs,
        "recommendation": analysis_result.get("recommendation", "iterate"),
        "recommendation_reason": analysis_result.get("recommendation_reason", ""),
    }
    
    if Template:
        html = Template(REPORT_TEMPLATE).render(**context)
    else:
        html = REPORT_TEMPLATE.replace("{{ experiment_id }}", experiment_id)
        for k, v in context.items():
            if v is not None and "{{ " + k + " }}" in html:
                html = html.replace("{{ " + k + " }}", str(v))
    
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(html)
    
    logger.info(f"Executive summary saved to {out_path}")
    return out_path
